export const link={
    "url": "https://api.github.com/repos/guyuezhai/interviewSummary/issues/22",
    "repository_url": "https://api.github.com/repos/guyuezhai/interviewSummary",
    "labels_url": "https://api.github.com/repos/guyuezhai/interviewSummary/issues/22/labels{/name}",
    "comments_url": "https://api.github.com/repos/guyuezhai/interviewSummary/issues/22/comments",
    "events_url": "https://api.github.com/repos/guyuezhai/interviewSummary/issues/22/events",
    "html_url": "https://github.com/guyuezhai/interviewSummary/issues/22",
    "id": 685195111,
    "node_id": "MDU6SXNzdWU2ODUxOTUxMTE=",
    "number": 22,
    "title": "react-router 的 <Link> 标签和 <a> 标签有什么区别",
    "user": {
      "login": "guyuezhai",
      "id": 24433701,
      "node_id": "MDQ6VXNlcjI0NDMzNzAx",
      "avatar_url": "https://avatars3.githubusercontent.com/u/24433701?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/guyuezhai",
      "html_url": "https://github.com/guyuezhai",
      "followers_url": "https://api.github.com/users/guyuezhai/followers",
      "following_url": "https://api.github.com/users/guyuezhai/following{/other_user}",
      "gists_url": "https://api.github.com/users/guyuezhai/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/guyuezhai/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/guyuezhai/subscriptions",
      "organizations_url": "https://api.github.com/users/guyuezhai/orgs",
      "repos_url": "https://api.github.com/users/guyuezhai/repos",
      "events_url": "https://api.github.com/users/guyuezhai/events{/privacy}",
      "received_events_url": "https://api.github.com/users/guyuezhai/received_events",
      "type": "User",
      "site_admin": false
    },
    "labels": [],
    "state": "open",
    "locked": false,
    "assignee": null,
    "assignees": [],
    "milestone": null,
    "comments": 0,
    "created_at": "2020-08-25T05:56:33Z",
    "updated_at": "2020-08-25T06:10:28Z",
    "closed_at": null,
    "author_association": "OWNER",
    "active_lock_reason": null,
    "body": "从最终渲染的DOM来看，这两者都是\\<a>标签，\r\n在react-router中\\<Link>标签需要配合\\<Route>标签做路由跳转，react-router接管了其默认的跳转行为，\r\n有别于传统的页面跳转，且\\<Link>的跳转只触发相匹配的\\<Route>对应页面内容更新，不会刷新整个页面。\r\n而\\<a>标签是普通的超链接，用于从当前页面跳转到href指向的另一个页面（非锚点情况）",
    "closed_by": null,
    "performed_via_github_app": null
  }
export const twosum={
  "url": "https://api.github.com/repos/guyuezhai/interviewSummary/issues/21",
  "repository_url": "https://api.github.com/repos/guyuezhai/interviewSummary",
  "labels_url": "https://api.github.com/repos/guyuezhai/interviewSummary/issues/21/labels{/name}",
  "comments_url": "https://api.github.com/repos/guyuezhai/interviewSummary/issues/21/comments",
  "events_url": "https://api.github.com/repos/guyuezhai/interviewSummary/issues/21/events",
  "html_url": "https://github.com/guyuezhai/interviewSummary/issues/21",
  "id": 684332667,
  "node_id": "MDU6SXNzdWU2ODQzMzI2Njc=",
  "number": 21,
  "title": " 两数之和",
  "user": {
    "login": "guyuezhai",
    "id": 24433701,
    "node_id": "MDQ6VXNlcjI0NDMzNzAx",
    "avatar_url": "https://avatars3.githubusercontent.com/u/24433701?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/guyuezhai",
    "html_url": "https://github.com/guyuezhai",
    "followers_url": "https://api.github.com/users/guyuezhai/followers",
    "following_url": "https://api.github.com/users/guyuezhai/following{/other_user}",
    "gists_url": "https://api.github.com/users/guyuezhai/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/guyuezhai/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/guyuezhai/subscriptions",
    "organizations_url": "https://api.github.com/users/guyuezhai/orgs",
    "repos_url": "https://api.github.com/users/guyuezhai/repos",
    "events_url": "https://api.github.com/users/guyuezhai/events{/privacy}",
    "received_events_url": "https://api.github.com/users/guyuezhai/received_events",
    "type": "User",
    "site_admin": false
  },
  "labels": [

  ],
  "state": "open",
  "locked": false,
  "assignee": null,
  "assignees": [

  ],
  "milestone": null,
  "comments": 1,
  "created_at": "2020-08-24T03:29:38Z",
  "updated_at": "2020-08-24T03:29:58Z",
  "closed_at": null,
  "author_association": "OWNER",
  "active_lock_reason": null,
  "body": "给定一个整数数组 nums 和一个目标值 target，请你在该数组中找出和为目标值的那 两个 整数，并返回他们的数组下标。\r\n\r\n你可以假设每种输入只会对应一个答案。但是，数组中同一个元素不能使用两遍。\r\n\r\n示例:\r\n> 给定 nums = [2, 7, 11, 15], target = 9\r\n因为 nums[0] + nums[1] = 2 + 7 = 9\r\n所以返回 [0, 1]\r\n",
  "closed_by": null,
  "performed_via_github_app": null
}

export const comments=[
  {
    "url": "https://api.github.com/repos/guyuezhai/interviewSummary/issues/comments/678884839",
    "html_url": "https://github.com/guyuezhai/interviewSummary/issues/21#issuecomment-678884839",
    "issue_url": "https://api.github.com/repos/guyuezhai/interviewSummary/issues/21",
    "id": 678884839,
    "node_id": "MDEyOklzc3VlQ29tbWVudDY3ODg4NDgzOQ==",
    "user": {
      "login": "guyuezhai",
      "id": 24433701,
      "node_id": "MDQ6VXNlcjI0NDMzNzAx",
      "avatar_url": "https://avatars3.githubusercontent.com/u/24433701?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/guyuezhai",
      "html_url": "https://github.com/guyuezhai",
      "followers_url": "https://api.github.com/users/guyuezhai/followers",
      "following_url": "https://api.github.com/users/guyuezhai/following{/other_user}",
      "gists_url": "https://api.github.com/users/guyuezhai/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/guyuezhai/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/guyuezhai/subscriptions",
      "organizations_url": "https://api.github.com/users/guyuezhai/orgs",
      "repos_url": "https://api.github.com/users/guyuezhai/repos",
      "events_url": "https://api.github.com/users/guyuezhai/events{/privacy}",
      "received_events_url": "https://api.github.com/users/guyuezhai/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2020-08-24T03:29:57Z",
    "updated_at": "2020-08-24T03:29:57Z",
    "author_association": "OWNER",
    "body": "```js\r\n/**\r\n * @param {number[]} nums\r\n * @param {number} target\r\n * @return {number[]}\r\n */\r\nvar twoSum = function(nums, target) {\r\n    let map=new Map(),loop=0;\r\n    while(loop<nums.length){\r\n        let item=nums[loop]\r\n        let index=target-item;\r\n        let flag=map.has(index)\r\n        if(flag){\r\n            return [map.get(index),loop]\r\n        }\r\n        map.set(item,loop)\r\n        loop++\r\n    }\r\n};\r\n```",
    "performed_via_github_app": null
  }
]
